import React, { useEffect, useState, useContext} from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import GoogleButton from '../components/google-button/google-button.component'
import cookies from "next-cookies";
import axiosInstance from '../services/axiosInstance'
import { AuthContext } from '../context/auth.context';
export default function Home(accessToken) {
  const { user, setAccessToken, isLoggedIn } = useContext(AuthContext);
  useEffect(() => {
    setAccessToken(accessToken);
  }, []);

  // const [isLoggedIn, setIsLoggedIn] = useState(false);
  // const [data, setData] = useState(null);

  // // useEffect(() => {
  // //   if(Object.keys(accessToken).lengthv > 0){
  // //     setIsLoggedIn(true);
  // //   } else {
  // //     setIsLoggedIn(false);
  // //   }
  // // }, [Object.keys(accessToken).length]);

  // useEffect(() => {
  //   console.log(accessToken);
  //   if(Object.keys(accessToken).length > 0){
  //     setIsLoggedIn(true);
  //   } else {
  //     setIsLoggedIn(false);
  //   }
  // }, [accessToken]);

  // if(Object.keys(accessToken).length > 0) {
  //   setIsLoggedIn(true);
  // } else {
  //   setIsLoggedIn(false);
  // }

  const fetchDetails = async () => {
    const res = await axiosInstance.get('/user/details');
    // console.log("RES: ", res.data);
    setData(res.data);
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">Journal Review System</a>
        </h1>

        <p className={styles.description}>
          This application is powered by NextJS! 🦾
        </p>

        {
          !isLoggedIn ? 
          <GoogleButton />
          : <h1>Logged in 🎉</h1>
        }
        {
          isLoggedIn && !user ? 
          <button onClick={fetchDetails}>GET YOUR DETAILS</button>
          : null
        }
        {
          user ?
          <div>
            <img src={user.user.picture}/>
            <h4>{user.user.username}</h4>
            <h4>{user.user.email}</h4>
          </div> : null
        }

        <p>* DELETE THE TOKEN FROM THE COOKIES TO LOG OUT 🤐*</p>
      </main>
    </div>
  )
}

Home.getInitialProps = async (ctx) => {
  const { accessToken } = cookies(ctx);
  return accessToken ? accessToken : {};
}